"use strict";
const TableInput_vue_vue_type_script_lang = require("./TableInput.vue_vue_type_script_lang.js");
const TableSelect_vue_vue_type_script_lang = require("./TableSelect.vue_vue_type_script_lang.js");
const TableSwitch_vue_vue_type_script_lang = require("./TableSwitch.vue_vue_type_script_lang.js");
const TableInputNumber_vue_vue_type_script_lang = require("./TableInputNumber.vue_vue_type_script_lang.js");
const TableDate_vue_vue_type_script_lang = require("./TableDate.vue_vue_type_script_lang.js");
const componentMap = /* @__PURE__ */ new Map();
componentMap.set("Input", TableInput_vue_vue_type_script_lang);
componentMap.set("Select", TableSelect_vue_vue_type_script_lang);
componentMap.set("Switch", TableSwitch_vue_vue_type_script_lang);
componentMap.set("InputNumber", TableInputNumber_vue_vue_type_script_lang);
componentMap.set("Date", TableDate_vue_vue_type_script_lang);
module.exports = componentMap;
